# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20161028_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=4, null=True),
        ),
    ]
