# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='nickname',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tcc.Occupation'),
        ),
    ]
