# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0002_auto_20160913_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Product name')),
                ('price', models.PositiveIntegerField(help_text='Cost in points', verbose_name='Price')),
                ('stock', models.IntegerField(default=-1, help_text='-1 means unlimited stock', verbose_name='Stock')),
                ('max_per_user', models.PositiveIntegerField(default=0, help_text='0 means no limit', verbose_name='Max purchases per user')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(blank=True, editable=False)),
                ('used_at', models.DateField(blank=True, editable=False, null=True)),
                ('purchase_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='money',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tcc.Employee'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tcc.Product'),
        ),
        migrations.AddField(
            model_name='employee',
            name='inventory',
            field=models.ManyToManyField(through='tcc.Purchase', to='tcc.Product'),
        ),
    ]
