# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
        ('tcc', '0004_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementMetricConfig',
            fields=[
                ('engagement_metric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='questionnaire.EngagementMetric')),
                ('icon_class', models.CharField(help_text='An icon class (eg: fontawesome) to be displayed.', max_length=25, verbose_name='Icon class')),
                ('is_staff', models.BooleanField(default=False, help_text='Should this metric be displayed only by staff?', verbose_name='Displayed only for staff')),
            ],
        ),
    ]
