# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0005_engagementmetricconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hiring_date',
            field=models.DateField(null=True),
        ),
    ]
