# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0007_auto_20160926_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='first_login',
            field=models.BooleanField(default=True, editable=False, help_text='Identify first login user.', verbose_name='Is his first login?'),
        ),
    ]
