# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 03:02
from __future__ import unicode_literals

import apps.tcc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0008_employee_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tcc.models.user_directory_path),
        )
    ]
