# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0012_auto_20161010_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='received_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
