# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0013_auto_20161010_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='level',
            field=models.PositiveIntegerField(choices=[(4, 'Platinum'), (3, 'Gold'), (2, 'Silver'), (1, 'Bronze')], editable=False, help_text='The level of importance of this goal', null=True),
        ),
    ]
