# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    def set_field_values(apps, schema_editor):
        Badge = apps.get_model("tcc", "Badge")

        db_alias = schema_editor.connection.alias
        for badge in Badge.objects.using(db_alias).filter(level__isnull=True):
            badge.level = badge.goal.level
            badge.save()

    dependencies = [
        ('tcc', '0014_badge_level'),
    ]

    operations = [
        migrations.RunPython(set_field_values),
        migrations.AlterField(
            model_name='badge',
            name='level',
            field=models.PositiveIntegerField(choices=[(4, 'Platinum'), (3, 'Gold'), (2, 'Silver'), (1, 'Bronze')], editable=False, help_text='The level of importance of this goal'),
        ),
    ]
