# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-29 02:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0018_auto_20161104_0402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'verbose_name': 'Badge', 'verbose_name_plural': 'Badges'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='engagementmetricconfig',
            options={'verbose_name': 'Engagement metric config', 'verbose_name_plural': 'Engagement metric configs'},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'verbose_name': 'Goal', 'verbose_name_plural': 'Goals'},
        ),
        migrations.AlterModelOptions(
            name='occupation',
            options={'verbose_name': 'Occupation', 'verbose_name_plural': 'Occupations'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='teamquestionnaire',
            options={'verbose_name': 'Team questionnaire', 'verbose_name_plural': 'Team questionnaires'},
        ),
        migrations.AlterModelOptions(
            name='teamquestionnairecontrol',
            options={'verbose_name': 'Team questionnaire control', 'verbose_name_plural': 'Team questionnaire controls'},
        ),
    ]
