# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-29 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0019_auto_20170329_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='language',
            field=models.CharField(choices=[('pt-br', 'Portuguese (BR)'), ('es', 'Spanish'), ('en-au', 'English (AU)')], default='pt-br', max_length=5, verbose_name='Language'),
        ),
    ]
