# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-05 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0021_employee_is_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='ends_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ends on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='frequency',
            field=models.PositiveIntegerField(choices=[(1, 'Once'), (2, 'Daily'), (3, 'Weekly'), (4, 'Monthly')], default=1, help_text='Frequency rate this goal happens'),
        ),
        migrations.AddField(
            model_name='goal',
            name='starts_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Starts on'),
            preserve_default=False,
        ),
    ]
